#### PANDAS
1. Pandas Dataframe
2. Pandas series
3. Pandas Basic Operations

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
## create a dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["row1","row2","row3","row4","row5"],columns=["column1","column2","column3","column4"])

In [7]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
df.head()# it show by default top 5 records

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [9]:
df.tail()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [10]:
df.head(2)

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int64
 1   column2  5 non-null      int64
 2   column3  5 non-null      int64
 3   column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [13]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [14]:
## Indexing
## direct using by column_name
## rowindex[Loc]location
## rowindex columnindex number[.iLoc]ilocation
df.head()


column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
## direct using by column_name
df[['column1','column2','column3']]#ek jada column chaiye toh nested list ka use karna hai

column1  column2  column3
row1        0        1        2
row2        4        5        6
row3        8        9       10
row4       12       13       14
row5       16       17       18

In [16]:
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int64

In [17]:
type(df['column1'])

pandas.core.series.Series

In [ ]:
##by using  row index name[Loc]location
df.loc['row3']

column1     8
column2     9
column3    10
column4    11
Name: row3, dtype: int64

In [22]:
df.loc[['row3','row4']]

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15

In [24]:
## rowindex columnindex number[.iLoc]ilocation
df.iloc[2:4,0:2]

column1  column2
row3        8        9
row4       12       13

In [28]:
df.iloc[2:5,1:4]

column2  column3  column4
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [34]:
df.iloc[0:5,0:4:3]

column1  column4
row1        0        3
row2        4        7
row3        8       11
row4       12       15
row5       16       19

In [36]:
## convert dataframes into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [37]:
## Basic Operations
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [40]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]] ,index=["row1","row2"],columns=["column1","column2","column3"])

In [41]:
df

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4

In [42]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [44]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [45]:
df['column3'].value_counts()

column3
2    1
4    1
Name: count, dtype: int64

In [46]:
df['column3'].unique()

array([2, 4])

In [ ]:
df[df['column2']>2]## conditional indexing

column1  column2  column3
row2        1      3.0        4