#### Numpy:->
* NumPy (Numerical Python) ek powerful Python library hai jo scientific computing aur array-based operations ke liye use hoti hai. Ye large data sets pe fast operations provide karta hai.
* NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python
- - -

### What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type
- - -

In [1]:
## import the library
import numpy as np

In [3]:
# single dimension array  for identifying:[] single array ,[[]] 2d array
lst=[1,2,3,4]
arr=np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(4,)

In [40]:
## 2D array
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr=np.array([lst1,lst2,lst3])
print(arr)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [ ]:
arr.shape## shape function batata hai ki NumPy array ka size kaisa hai, yaani usme kitne rows aur columns (ya dimensions) hain.here 3 indicate 3rows and 4 indicate 4 columns

(3, 4)

In [ ]:
## array ki value change karna
lst=[1,2,3,4,5]
arr1=np.array(lst)
print(arr1)

[1 2 3 4 5]


In [23]:
arr1[3]=6
print(arr1)

[1 2 3 6 5]


In [26]:
arr1[1:]

array([2, 3, 6, 5])

In [ ]:
arr1[:-1]## last element ko delete kar dijye

array([1, 2, 3, 6])

In [ ]:
arr1[::-1]## apne aap reverse ho jata hai

array([5, 6, 3, 2, 1])

In [31]:
arr1[::-2]## two two jump hoke print hoga

array([5, 3, 1])

In [41]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [49]:
#arr[rows,columns]
arr[:,1]

array([2, 3, 4])

In [52]:
arr[1:,1:3]

array([[3, 4],
       [4, 5]])

In [53]:
arr[1:,3:5]

array([[5, 6],
       [6, 7]])

In [55]:
arr[:,3:].shape

(3, 2)

In [62]:
arr[0:,[0,4]]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [64]:
## EDA point of you
arr1

array([1, 2, 3, 6, 5])

In [67]:
arr1<2

array([ True, False, False, False, False])

In [ ]:
arr[arr<2]# it print specific that will be less than 2

array([1])

In [69]:
arr.shape

(3, 5)

In [ ]:
## reshape:->reshape() function ka use array ka shape (form) badalne ke liye hota hai — bina data ko badle. Aap 1D array ko 2D, 2D ko 3D, etc. me convert kar sakte ho jab tak total elements same ho.
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [ ]:
## mechanism to create an array 
# arange function
#np.arange(start,stop,stepsize)
np.arange(1,10,1)#np.arange() is a NumPy function used to generate a sequence of numbers (like Python’s range()), but it returns a NumPy array instead of a list.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,20,2).reshape(2,5)##2D

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [75]:
np.arange(1,20,2).reshape(1,10,1)##3D

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [76]:
arr1

array([1, 2, 3, 6, 5])

In [77]:
arr1*arr1

array([ 1,  4,  9, 36, 25])

In [78]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [79]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.random.randint(10,50,4)## 10 is low, 50 is high and 4 means it will print 4 numbers

array([38, 38, 22, 40], dtype=int32)

In [83]:
np.random.randint(10,50,4).reshape(2,2)

array([[19, 25],
       [48, 21]], dtype=int32)

In [84]:
np.random.randn(5,6)

array([[-0.88221442, -1.81017669,  0.90324296, -0.10865233, -1.21194491,
         1.09792807],
       [ 1.04631035, -0.60583359, -0.07375635, -0.67784396, -0.2625069 ,
         0.31167869],
       [-2.28044868, -1.08196843, -1.22308892,  1.34622273, -0.19200643,
         0.42800288],
       [-0.30022149,  1.53714498, -2.11840914,  1.61906722,  0.56471877,
        -0.79338232],
       [ 1.39906951,  1.49714612,  0.85943513,  0.66912456,  1.07182297,
         0.53393167]])

In [85]:
np.random.random_sample((4,7))

array([[0.2164319 , 0.04193183, 0.63568746, 0.84177073, 0.86135432,
        0.66324808, 0.75040809],
       [0.2584795 , 0.84159301, 0.98610558, 0.95552417, 0.70094375,
        0.45288609, 0.31140988],
       [0.24216357, 0.69842657, 0.98553784, 0.65729432, 0.19397659,
        0.77589587, 0.72304219],
       [0.85131585, 0.83010919, 0.2141001 , 0.96048579, 0.29611519,
        0.78510508, 0.93607288]])

In [5]:
import numpy as np

In [6]:
## 2D array
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr=np.array([lst1,lst2,lst3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [ ]:
arr.flatten()#convert 2d into 1d


array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7])

In [ ]:
arr.ravel()#convert 2d into 1d

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7])

In [ ]:
arr.T## Transpose of array

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [13]:
import numpy as np

arr = np.linspace(1, 10, 5)
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]
